name: CI

on:
  push:
    branches: ['master', 'main']
    schedule:
      - cron: '5 16 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Node.js v14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Npm Install
      run: npm install

    - name: Run Script
      run: node ./index.js > ./result.log